// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interconnection.proto

package interconnection;

public final class Interconnection {
  private Interconnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface command_typeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interconnection.command_type)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .interconnection.command_type.command_t type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .interconnection.command_type.command_t type = 1;</code>
     */
    interconnection.Interconnection.command_type.command_t getType();

    /**
     * <code>required int32 version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 2;</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code interconnection.command_type}
   */
  public  static final class command_type extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:interconnection.command_type)
      command_typeOrBuilder {
    // Use command_type.newBuilder() to construct.
    private command_type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private command_type() {
      type_ = 0;
      version_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private command_type(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              interconnection.Interconnection.command_type.command_t value = interconnection.Interconnection.command_type.command_t.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interconnection.Interconnection.internal_static_interconnection_command_type_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interconnection.Interconnection.internal_static_interconnection_command_type_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interconnection.Interconnection.command_type.class, interconnection.Interconnection.command_type.Builder.class);
    }

    /**
     * Protobuf enum {@code interconnection.command_type.command_t}
     */
    public enum command_t
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>DRONE_COORDINATES = 1;</code>
       */
      DRONE_COORDINATES(1),
      /**
       * <code>MISSION_START = 2;</code>
       */
      MISSION_START(2),
      /**
       * <code>MISSION_PAUSE = 3;</code>
       */
      MISSION_PAUSE(3),
      /**
       * <code>MISSION_CONTINUE = 4;</code>
       */
      MISSION_CONTINUE(4),
      /**
       * <code>MISSION_ABORT = 5;</code>
       */
      MISSION_ABORT(5),
      /**
       * <code>LASER_RANGE = 6;</code>
       */
      LASER_RANGE(6),
      /**
       * <code>ERROR_UNEXPECTED_COMMAND = 7;</code>
       */
      ERROR_UNEXPECTED_COMMAND(7),
      /**
       * <code>ERROR_MISSION_ALREADY_EXECUTING = 8;</code>
       */
      ERROR_MISSION_ALREADY_EXECUTING(8),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>DRONE_COORDINATES = 1;</code>
       */
      public static final int DRONE_COORDINATES_VALUE = 1;
      /**
       * <code>MISSION_START = 2;</code>
       */
      public static final int MISSION_START_VALUE = 2;
      /**
       * <code>MISSION_PAUSE = 3;</code>
       */
      public static final int MISSION_PAUSE_VALUE = 3;
      /**
       * <code>MISSION_CONTINUE = 4;</code>
       */
      public static final int MISSION_CONTINUE_VALUE = 4;
      /**
       * <code>MISSION_ABORT = 5;</code>
       */
      public static final int MISSION_ABORT_VALUE = 5;
      /**
       * <code>LASER_RANGE = 6;</code>
       */
      public static final int LASER_RANGE_VALUE = 6;
      /**
       * <code>ERROR_UNEXPECTED_COMMAND = 7;</code>
       */
      public static final int ERROR_UNEXPECTED_COMMAND_VALUE = 7;
      /**
       * <code>ERROR_MISSION_ALREADY_EXECUTING = 8;</code>
       */
      public static final int ERROR_MISSION_ALREADY_EXECUTING_VALUE = 8;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static command_t valueOf(int value) {
        return forNumber(value);
      }

      public static command_t forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return DRONE_COORDINATES;
          case 2: return MISSION_START;
          case 3: return MISSION_PAUSE;
          case 4: return MISSION_CONTINUE;
          case 5: return MISSION_ABORT;
          case 6: return LASER_RANGE;
          case 7: return ERROR_UNEXPECTED_COMMAND;
          case 8: return ERROR_MISSION_ALREADY_EXECUTING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<command_t>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          command_t> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<command_t>() {
              public command_t findValueByNumber(int number) {
                return command_t.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return interconnection.Interconnection.command_type.getDescriptor().getEnumTypes().get(0);
      }

      private static final command_t[] VALUES = values();

      public static command_t valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private command_t(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:interconnection.command_type.command_t)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .interconnection.command_type.command_t type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .interconnection.command_type.command_t type = 1;</code>
     */
    public interconnection.Interconnection.command_type.command_t getType() {
      interconnection.Interconnection.command_type.command_t result = interconnection.Interconnection.command_type.command_t.valueOf(type_);
      return result == null ? interconnection.Interconnection.command_type.command_t.PING : result;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>required int32 version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, version_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof interconnection.Interconnection.command_type)) {
        return super.equals(obj);
      }
      interconnection.Interconnection.command_type other = (interconnection.Interconnection.command_type) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static interconnection.Interconnection.command_type parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.command_type parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.command_type parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.command_type parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.command_type parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.command_type parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.command_type parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.command_type parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.command_type parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.command_type parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(interconnection.Interconnection.command_type prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interconnection.command_type}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interconnection.command_type)
        interconnection.Interconnection.command_typeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interconnection.Interconnection.internal_static_interconnection_command_type_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interconnection.Interconnection.internal_static_interconnection_command_type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interconnection.Interconnection.command_type.class, interconnection.Interconnection.command_type.Builder.class);
      }

      // Construct using interconnection.Interconnection.command_type.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interconnection.Interconnection.internal_static_interconnection_command_type_descriptor;
      }

      public interconnection.Interconnection.command_type getDefaultInstanceForType() {
        return interconnection.Interconnection.command_type.getDefaultInstance();
      }

      public interconnection.Interconnection.command_type build() {
        interconnection.Interconnection.command_type result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interconnection.Interconnection.command_type buildPartial() {
        interconnection.Interconnection.command_type result = new interconnection.Interconnection.command_type(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interconnection.Interconnection.command_type) {
          return mergeFrom((interconnection.Interconnection.command_type)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interconnection.Interconnection.command_type other) {
        if (other == interconnection.Interconnection.command_type.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interconnection.Interconnection.command_type parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interconnection.Interconnection.command_type) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .interconnection.command_type.command_t type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .interconnection.command_type.command_t type = 1;</code>
       */
      public interconnection.Interconnection.command_type.command_t getType() {
        interconnection.Interconnection.command_type.command_t result = interconnection.Interconnection.command_type.command_t.valueOf(type_);
        return result == null ? interconnection.Interconnection.command_type.command_t.PING : result;
      }
      /**
       * <code>required .interconnection.command_type.command_t type = 1;</code>
       */
      public Builder setType(interconnection.Interconnection.command_type.command_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .interconnection.command_type.command_t type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required int32 version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:interconnection.command_type)
    }

    // @@protoc_insertion_point(class_scope:interconnection.command_type)
    private static final interconnection.Interconnection.command_type DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new interconnection.Interconnection.command_type();
    }

    public static interconnection.Interconnection.command_type getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<command_type>
        PARSER = new com.google.protobuf.AbstractParser<command_type>() {
      public command_type parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new command_type(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<command_type> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<command_type> getParserForType() {
      return PARSER;
    }

    public interconnection.Interconnection.command_type getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface drone_coordinatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interconnection.drone_coordinates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();

    /**
     * <code>required float heading = 3;</code>
     */
    boolean hasHeading();
    /**
     * <code>required float heading = 3;</code>
     */
    float getHeading();

    /**
     * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
     */
    boolean hasState();
    /**
     * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
     */
    interconnection.Interconnection.drone_coordinates.state_t getState();
  }
  /**
   * Protobuf type {@code interconnection.drone_coordinates}
   */
  public  static final class drone_coordinates extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:interconnection.drone_coordinates)
      drone_coordinatesOrBuilder {
    // Use drone_coordinates.newBuilder() to construct.
    private drone_coordinates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private drone_coordinates() {
      latitude_ = 0D;
      longitude_ = 0D;
      heading_ = 0F;
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private drone_coordinates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              heading_ = input.readFloat();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              interconnection.Interconnection.drone_coordinates.state_t value = interconnection.Interconnection.drone_coordinates.state_t.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                state_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interconnection.Interconnection.internal_static_interconnection_drone_coordinates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interconnection.Interconnection.internal_static_interconnection_drone_coordinates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interconnection.Interconnection.drone_coordinates.class, interconnection.Interconnection.drone_coordinates.Builder.class);
    }

    /**
     * Protobuf enum {@code interconnection.drone_coordinates.state_t}
     */
    public enum state_t
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READY = 0;</code>
       */
      READY(0),
      /**
       * <code>WAITING = 1;</code>
       */
      WAITING(1),
      /**
       * <code>PAUSED = 2;</code>
       */
      PAUSED(2),
      /**
       * <code>EXECUTING = 3;</code>
       */
      EXECUTING(3),
      ;

      /**
       * <code>READY = 0;</code>
       */
      public static final int READY_VALUE = 0;
      /**
       * <code>WAITING = 1;</code>
       */
      public static final int WAITING_VALUE = 1;
      /**
       * <code>PAUSED = 2;</code>
       */
      public static final int PAUSED_VALUE = 2;
      /**
       * <code>EXECUTING = 3;</code>
       */
      public static final int EXECUTING_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static state_t valueOf(int value) {
        return forNumber(value);
      }

      public static state_t forNumber(int value) {
        switch (value) {
          case 0: return READY;
          case 1: return WAITING;
          case 2: return PAUSED;
          case 3: return EXECUTING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<state_t>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          state_t> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<state_t>() {
              public state_t findValueByNumber(int number) {
                return state_t.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return interconnection.Interconnection.drone_coordinates.getDescriptor().getEnumTypes().get(0);
      }

      private static final state_t[] VALUES = values();

      public static state_t valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private state_t(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:interconnection.drone_coordinates.state_t)
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int HEADING_FIELD_NUMBER = 3;
    private float heading_;
    /**
     * <code>required float heading = 3;</code>
     */
    public boolean hasHeading() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float heading = 3;</code>
     */
    public float getHeading() {
      return heading_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
     */
    public interconnection.Interconnection.drone_coordinates.state_t getState() {
      interconnection.Interconnection.drone_coordinates.state_t result = interconnection.Interconnection.drone_coordinates.state_t.valueOf(state_);
      return result == null ? interconnection.Interconnection.drone_coordinates.state_t.READY : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, heading_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, state_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, heading_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof interconnection.Interconnection.drone_coordinates)) {
        return super.equals(obj);
      }
      interconnection.Interconnection.drone_coordinates other = (interconnection.Interconnection.drone_coordinates) obj;

      boolean result = true;
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && (hasHeading() == other.hasHeading());
      if (hasHeading()) {
        result = result && (
            java.lang.Float.floatToIntBits(getHeading())
            == java.lang.Float.floatToIntBits(
                other.getHeading()));
      }
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && state_ == other.state_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasHeading()) {
        hash = (37 * hash) + HEADING_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getHeading());
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static interconnection.Interconnection.drone_coordinates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.drone_coordinates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.drone_coordinates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.drone_coordinates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(interconnection.Interconnection.drone_coordinates prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interconnection.drone_coordinates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interconnection.drone_coordinates)
        interconnection.Interconnection.drone_coordinatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interconnection.Interconnection.internal_static_interconnection_drone_coordinates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interconnection.Interconnection.internal_static_interconnection_drone_coordinates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interconnection.Interconnection.drone_coordinates.class, interconnection.Interconnection.drone_coordinates.Builder.class);
      }

      // Construct using interconnection.Interconnection.drone_coordinates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        heading_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interconnection.Interconnection.internal_static_interconnection_drone_coordinates_descriptor;
      }

      public interconnection.Interconnection.drone_coordinates getDefaultInstanceForType() {
        return interconnection.Interconnection.drone_coordinates.getDefaultInstance();
      }

      public interconnection.Interconnection.drone_coordinates build() {
        interconnection.Interconnection.drone_coordinates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interconnection.Interconnection.drone_coordinates buildPartial() {
        interconnection.Interconnection.drone_coordinates result = new interconnection.Interconnection.drone_coordinates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.heading_ = heading_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interconnection.Interconnection.drone_coordinates) {
          return mergeFrom((interconnection.Interconnection.drone_coordinates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interconnection.Interconnection.drone_coordinates other) {
        if (other == interconnection.Interconnection.drone_coordinates.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasHeading()) {
          setHeading(other.getHeading());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasHeading()) {
          return false;
        }
        if (!hasState()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interconnection.Interconnection.drone_coordinates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interconnection.Interconnection.drone_coordinates) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private float heading_ ;
      /**
       * <code>required float heading = 3;</code>
       */
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float heading = 3;</code>
       */
      public float getHeading() {
        return heading_;
      }
      /**
       * <code>required float heading = 3;</code>
       */
      public Builder setHeading(float value) {
        bitField0_ |= 0x00000004;
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float heading = 3;</code>
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heading_ = 0F;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
       */
      public interconnection.Interconnection.drone_coordinates.state_t getState() {
        interconnection.Interconnection.drone_coordinates.state_t result = interconnection.Interconnection.drone_coordinates.state_t.valueOf(state_);
        return result == null ? interconnection.Interconnection.drone_coordinates.state_t.READY : result;
      }
      /**
       * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
       */
      public Builder setState(interconnection.Interconnection.drone_coordinates.state_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .interconnection.drone_coordinates.state_t state = 4;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:interconnection.drone_coordinates)
    }

    // @@protoc_insertion_point(class_scope:interconnection.drone_coordinates)
    private static final interconnection.Interconnection.drone_coordinates DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new interconnection.Interconnection.drone_coordinates();
    }

    public static interconnection.Interconnection.drone_coordinates getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<drone_coordinates>
        PARSER = new com.google.protobuf.AbstractParser<drone_coordinates>() {
      public drone_coordinates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new drone_coordinates(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<drone_coordinates> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<drone_coordinates> getParserForType() {
      return PARSER;
    }

    public interconnection.Interconnection.drone_coordinates getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface pin_coordinatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interconnection.pin_coordinates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code interconnection.pin_coordinates}
   */
  public  static final class pin_coordinates extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:interconnection.pin_coordinates)
      pin_coordinatesOrBuilder {
    // Use pin_coordinates.newBuilder() to construct.
    private pin_coordinates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pin_coordinates() {
      latitude_ = 0D;
      longitude_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pin_coordinates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interconnection.Interconnection.internal_static_interconnection_pin_coordinates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interconnection.Interconnection.internal_static_interconnection_pin_coordinates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interconnection.Interconnection.pin_coordinates.class, interconnection.Interconnection.pin_coordinates.Builder.class);
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof interconnection.Interconnection.pin_coordinates)) {
        return super.equals(obj);
      }
      interconnection.Interconnection.pin_coordinates other = (interconnection.Interconnection.pin_coordinates) obj;

      boolean result = true;
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static interconnection.Interconnection.pin_coordinates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.pin_coordinates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.pin_coordinates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.pin_coordinates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(interconnection.Interconnection.pin_coordinates prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interconnection.pin_coordinates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interconnection.pin_coordinates)
        interconnection.Interconnection.pin_coordinatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interconnection.Interconnection.internal_static_interconnection_pin_coordinates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interconnection.Interconnection.internal_static_interconnection_pin_coordinates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interconnection.Interconnection.pin_coordinates.class, interconnection.Interconnection.pin_coordinates.Builder.class);
      }

      // Construct using interconnection.Interconnection.pin_coordinates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interconnection.Interconnection.internal_static_interconnection_pin_coordinates_descriptor;
      }

      public interconnection.Interconnection.pin_coordinates getDefaultInstanceForType() {
        return interconnection.Interconnection.pin_coordinates.getDefaultInstance();
      }

      public interconnection.Interconnection.pin_coordinates build() {
        interconnection.Interconnection.pin_coordinates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interconnection.Interconnection.pin_coordinates buildPartial() {
        interconnection.Interconnection.pin_coordinates result = new interconnection.Interconnection.pin_coordinates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interconnection.Interconnection.pin_coordinates) {
          return mergeFrom((interconnection.Interconnection.pin_coordinates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interconnection.Interconnection.pin_coordinates other) {
        if (other == interconnection.Interconnection.pin_coordinates.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interconnection.Interconnection.pin_coordinates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interconnection.Interconnection.pin_coordinates) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:interconnection.pin_coordinates)
    }

    // @@protoc_insertion_point(class_scope:interconnection.pin_coordinates)
    private static final interconnection.Interconnection.pin_coordinates DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new interconnection.Interconnection.pin_coordinates();
    }

    public static interconnection.Interconnection.pin_coordinates getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<pin_coordinates>
        PARSER = new com.google.protobuf.AbstractParser<pin_coordinates>() {
      public pin_coordinates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new pin_coordinates(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pin_coordinates> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pin_coordinates> getParserForType() {
      return PARSER;
    }

    public interconnection.Interconnection.pin_coordinates getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface laser_rangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:interconnection.laser_range)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float range = 1;</code>
     */
    boolean hasRange();
    /**
     * <code>required float range = 1;</code>
     */
    float getRange();
  }
  /**
   * Protobuf type {@code interconnection.laser_range}
   */
  public  static final class laser_range extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:interconnection.laser_range)
      laser_rangeOrBuilder {
    // Use laser_range.newBuilder() to construct.
    private laser_range(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private laser_range() {
      range_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private laser_range(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              range_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return interconnection.Interconnection.internal_static_interconnection_laser_range_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return interconnection.Interconnection.internal_static_interconnection_laser_range_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              interconnection.Interconnection.laser_range.class, interconnection.Interconnection.laser_range.Builder.class);
    }

    private int bitField0_;
    public static final int RANGE_FIELD_NUMBER = 1;
    private float range_;
    /**
     * <code>required float range = 1;</code>
     */
    public boolean hasRange() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float range = 1;</code>
     */
    public float getRange() {
      return range_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, range_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, range_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof interconnection.Interconnection.laser_range)) {
        return super.equals(obj);
      }
      interconnection.Interconnection.laser_range other = (interconnection.Interconnection.laser_range) obj;

      boolean result = true;
      result = result && (hasRange() == other.hasRange());
      if (hasRange()) {
        result = result && (
            java.lang.Float.floatToIntBits(getRange())
            == java.lang.Float.floatToIntBits(
                other.getRange()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRange()) {
        hash = (37 * hash) + RANGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRange());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static interconnection.Interconnection.laser_range parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.laser_range parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.laser_range parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static interconnection.Interconnection.laser_range parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static interconnection.Interconnection.laser_range parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.laser_range parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.laser_range parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.laser_range parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static interconnection.Interconnection.laser_range parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static interconnection.Interconnection.laser_range parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(interconnection.Interconnection.laser_range prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code interconnection.laser_range}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:interconnection.laser_range)
        interconnection.Interconnection.laser_rangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return interconnection.Interconnection.internal_static_interconnection_laser_range_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return interconnection.Interconnection.internal_static_interconnection_laser_range_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                interconnection.Interconnection.laser_range.class, interconnection.Interconnection.laser_range.Builder.class);
      }

      // Construct using interconnection.Interconnection.laser_range.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        range_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return interconnection.Interconnection.internal_static_interconnection_laser_range_descriptor;
      }

      public interconnection.Interconnection.laser_range getDefaultInstanceForType() {
        return interconnection.Interconnection.laser_range.getDefaultInstance();
      }

      public interconnection.Interconnection.laser_range build() {
        interconnection.Interconnection.laser_range result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public interconnection.Interconnection.laser_range buildPartial() {
        interconnection.Interconnection.laser_range result = new interconnection.Interconnection.laser_range(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.range_ = range_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof interconnection.Interconnection.laser_range) {
          return mergeFrom((interconnection.Interconnection.laser_range)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(interconnection.Interconnection.laser_range other) {
        if (other == interconnection.Interconnection.laser_range.getDefaultInstance()) return this;
        if (other.hasRange()) {
          setRange(other.getRange());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRange()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        interconnection.Interconnection.laser_range parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (interconnection.Interconnection.laser_range) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float range_ ;
      /**
       * <code>required float range = 1;</code>
       */
      public boolean hasRange() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float range = 1;</code>
       */
      public float getRange() {
        return range_;
      }
      /**
       * <code>required float range = 1;</code>
       */
      public Builder setRange(float value) {
        bitField0_ |= 0x00000001;
        range_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float range = 1;</code>
       */
      public Builder clearRange() {
        bitField0_ = (bitField0_ & ~0x00000001);
        range_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:interconnection.laser_range)
    }

    // @@protoc_insertion_point(class_scope:interconnection.laser_range)
    private static final interconnection.Interconnection.laser_range DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new interconnection.Interconnection.laser_range();
    }

    public static interconnection.Interconnection.laser_range getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<laser_range>
        PARSER = new com.google.protobuf.AbstractParser<laser_range>() {
      public laser_range parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new laser_range(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<laser_range> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<laser_range> getParserForType() {
      return PARSER;
    }

    public interconnection.Interconnection.laser_range getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interconnection_command_type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_interconnection_command_type_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interconnection_drone_coordinates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_interconnection_drone_coordinates_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interconnection_pin_coordinates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_interconnection_pin_coordinates_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_interconnection_laser_range_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_interconnection_laser_range_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025interconnection.proto\022\017interconnection" +
      "\"\250\002\n\014command_type\0225\n\004type\030\001 \002(\0162\'.interc" +
      "onnection.command_type.command_t\022\017\n\007vers" +
      "ion\030\002 \002(\005\"\317\001\n\tcommand_t\022\010\n\004PING\020\000\022\025\n\021DRO" +
      "NE_COORDINATES\020\001\022\021\n\rMISSION_START\020\002\022\021\n\rM" +
      "ISSION_PAUSE\020\003\022\024\n\020MISSION_CONTINUE\020\004\022\021\n\r" +
      "MISSION_ABORT\020\005\022\017\n\013LASER_RANGE\020\006\022\034\n\030ERRO" +
      "R_UNEXPECTED_COMMAND\020\007\022#\n\037ERROR_MISSION_" +
      "ALREADY_EXECUTING\020\010\"\302\001\n\021drone_coordinate" +
      "s\022\020\n\010latitude\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\022\017",
      "\n\007heading\030\003 \002(\002\0229\n\005state\030\004 \002(\0162*.interco" +
      "nnection.drone_coordinates.state_t\"<\n\007st" +
      "ate_t\022\t\n\005READY\020\000\022\013\n\007WAITING\020\001\022\n\n\006PAUSED\020" +
      "\002\022\r\n\tEXECUTING\020\003\"6\n\017pin_coordinates\022\020\n\010l" +
      "atitude\030\001 \002(\001\022\021\n\tlongitude\030\002 \002(\001\"\034\n\013lase" +
      "r_range\022\r\n\005range\030\001 \002(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_interconnection_command_type_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_interconnection_command_type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_interconnection_command_type_descriptor,
        new java.lang.String[] { "Type", "Version", });
    internal_static_interconnection_drone_coordinates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_interconnection_drone_coordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_interconnection_drone_coordinates_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Heading", "State", });
    internal_static_interconnection_pin_coordinates_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_interconnection_pin_coordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_interconnection_pin_coordinates_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_interconnection_laser_range_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_interconnection_laser_range_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_interconnection_laser_range_descriptor,
        new java.lang.String[] { "Range", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
