name: CMake

on:
  push:
    branches-ignore:
    - 'wip.*'
    - 'pr.*'
    - 'html_deploy'
    tags:
    - 'v*'
  release:
    types: [published, created, released]
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners
        include:
          - os: ubuntu-22.04
            build_type: Release
            clang_checks: false
            cross: false
            alias: ci_gcc
          - os: ubuntu-22.04
            build_type: Release
            clang_checks: true
            cross: false
            alias: ci_clang
          - os: ubuntu-22.04
            build_type: Release
            clang_checks: false
            cross: true
            alias: ci_jetson_cross
          - os: ubuntu-22.04
            build_type: Release
            clang_checks: false
            cross: true
            alias: ci_jetson_cross_sim_only
          - os: ubuntu-22.04
            build_type: Release
            clang_checks: false
            cross: true
            alias: ci_jetson_cross_sim_interconnection

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.OLYSEUS_BOT_SSH_PRIVATE_KEY }}
        submodules: true

    # https://github.com/actions/runner-images/issues/675#issuecomment-1419388451
    - name: Tweak APT
      run: |
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        sudo apt -y update

    - name: Install system dependencies
      run: |
        sudo apt install -y libboost-all-dev
        sudo apt install -y libjpeg-dev
        sudo apt install -y libopencv-dev
        sudo apt install -y libeigen3-dev
        sudo apt install -y libgmp-dev
        sudo apt install -y libmpfr-dev

    - name: Install Doxygen
      run: |
        sudo apt install -y doxygen
        sudo apt install -y graphviz
        sudo apt install -y libjs-mathjax

    - name: Install Ninja
      run: sudo apt install -y ninja-build

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/_builds /home/runner/opt ${{github.workspace}}/_deps

    # Clang 16.0.1 {
    - uses: robinraju/release-downloader@v1.8
      if: ${{ matrix.clang_checks }}
      with:
        repository: "Olyseus/i_seed_drone_onboard"
        tag: "v0.0.1"
        fileName: "Clang-16.0.1-Ubuntu-22.04.tar.gz"
        out-file-path: "${{github.workspace}}/_deps"
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Install Clang
      if: ${{ matrix.clang_checks }}
      run: tar xf "${{github.workspace}}/_deps/Clang-16.0.1-Ubuntu-22.04.tar.gz" -C "${{github.workspace}}/_deps/"

    - name: Add Clang to PATH
      if: ${{ matrix.clang_checks }}
      run: echo "${{github.workspace}}/_deps/LLVM-16.0.1-Linux/bin/" >> $GITHUB_PATH
    # }

    # jetson_cross {
    - uses: robinraju/release-downloader@v1.8
      if: ${{ matrix.cross }}
      with:
        repository: "Olyseus/i_seed_drone_onboard"
        tag: "v0.0.9"
        fileName: "jetson_cross.tar.gz"
        out-file-path: "${{github.workspace}}/_deps"
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Install jetson_cross
      if: ${{ matrix.cross }}
      run: tar xf "${{github.workspace}}/_deps/jetson_cross.tar.gz" -C "${{github.workspace}}/_deps/"

    - name: Add jetson_cross to PATH
      if: ${{ matrix.cross }}
      run: echo "${{github.workspace}}/_deps/jetson_cross/bin/" >> $GITHUB_PATH
    # }

    # googletest {
    - name: cache_googletest
      id: cache_googletest
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/googletest'
        key: '${{runner.os}}_googletest_1_11_0_${{matrix.build_type}}_cache'

    - name: install_googletest
      if: ${{ !steps.cache_googletest.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_googletest.cmake
    # }

    # spdlog {
    - name: cache_spdlog
      id: cache_spdlog
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/spdlog'
        key: '${{runner.os}}_spdlog_1_9_0_${{matrix.build_type}}_cache'

    - name: install_spdlog
      if: ${{ !steps.cache_spdlog.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_spdlog.cmake
    # }

    # cli11 {
    - name: cache_cli11
      id: cache_cli11
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/cli11'
        key: '${{runner.os}}_cli11_1_9_1_${{matrix.build_type}}_cache'

    - name: install_cli11
      if: ${{ !steps.cache_cli11.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_cli11.cmake
    # }

    # cgal {
    - name: cache_cgal
      id: cache_cgal
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/cgal'
        key: '${{runner.os}}_cgal_5_5_${{matrix.build_type}}_cache'

    - name: install_cgal
      if: ${{ !steps.cache_cgal.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_cgal.cmake
    # }

    # nlohmann_json {
    - name: cache_nlohmann_json
      id: cache_nlohmann_json
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/nlohmann_json'
        key: '${{runner.os}}_nlohmann_json_3_10_3_${{matrix.build_type}}_cache'

    - name: install_nlohmann_json
      if: ${{ !steps.cache_nlohmann_json.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_nlohmann_json.cmake
    # }

    # geographiclib {
    - name: cache_geographiclib
      id: cache_geographiclib
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/geographiclib'
        key: '${{runner.os}}_geographiclib_2_1_1_${{matrix.build_type}}_cache'

    - name: install_geographiclib
      if: ${{ !steps.cache_geographiclib.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_geographiclib.cmake
    # }

    # protobuf {
    - name: cache_protobuf
      id: cache_protobuf
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}/_deps/protobuf'
        key: '${{runner.os}}_protobuf_3_0_0_${{matrix.build_type}}_cache'

    - name: install_protobuf
      if: ${{ !steps.cache_protobuf.outputs.cache-hit }}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/_deps" -P third_party/dependencies/cmake/script/install_protobuf.cmake
    # }

    - name: Check format
      working-directory: ${{github.workspace}}
      if: ${{ matrix.clang_checks }}
      run: /bin/bash ./check_format.sh

    - name: Configure
      working-directory: ${{github.workspace}}/
      run: >
        cmake
        -B "${{github.workspace}}/_builds"
        -G Ninja
        -W no-dev
        -C "cmake/cache/${{matrix.alias}}.cmake"
        -D CMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: ${{github.workspace}}/_builds
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      if: ${{ !matrix.cross }}
      working-directory: ${{github.workspace}}/_builds
      run: ctest -VV -C ${{matrix.build_type}}

    - name: Pack
      if: ${{ matrix.cross }}
      working-directory: ${{github.workspace}}/_builds
      run: |
        cpack -G DEB -B ${{github.workspace}}/_pack -C ${{matrix.build_type}} --verbose
        cmake -E remove_directory ${{github.workspace}}/_pack/_CPack_Packages/

    - name: Upload release
      if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.build_type == 'Release' && matrix.cross }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ${{github.workspace}}/_pack/*
        asset_name: ${{matrix.asset_name}}
        tag: ${{github.ref}}
        overwrite: true
        file_glob: true

    - name: Pack documentation
      if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.build_type == 'Release' && !matrix.clang_checks && !matrix.cross }}
      working-directory: ${{github.workspace}}/_builds
      run: cmake -E tar czvf "${{github.ref_name}}-doxygen.tar.gz" html/

    - name: Upload documentation
      if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.build_type == 'Release' && !matrix.clang_checks && !matrix.cross }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ${{github.workspace}}/_builds/*-doxygen.tar.gz
        asset_name: ${{matrix.asset_name}}
        tag: ${{github.ref}}
        overwrite: true
        file_glob: true

    - name: Push to deploy branch
      working-directory: ${{github.workspace}}
      if: ${{ github.ref == 'refs/heads/master' && matrix.build_type == 'Release' && !matrix.clang_checks && !matrix.cross }}
      run: |
        mv _builds/html/ __generated_html/
        rm -rf docs/
        mv __generated_html/ docs/
        git rm -f third_party/dependencies/ # remove submodules
        touch .nojekyll docs/.nojekyll # https://stackoverflow.com/a/62967771
        git add docs/ .nojekyll
        git config user.email "x@ruslo.dev" # People with admin or maintainer permissions...
        git config user.name "Ruslan Baratov"
        git commit -m '[GitHub Action] Deploy documentation'
        git checkout -b html_deploy
        git push -f origin html_deploy:html_deploy
